# Generated by Django 4.2.7 on 2023-11-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0006_alter_historicalperformance_average_response_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('Fulfilled', 'Fulfilled')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
